#!/usr/bin/env bash
# Production / staging deploy helper — Railway (API) + Vercel (web/app)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  VIRLUX deploy — Railway API + Vercel web/app            ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Staging wire: npm run staging:wire  (needs RAILWAY_TOKEN + VERCEL_TOKEN)"
echo "Env template: .env.staging.example"
echo ""
echo "── Railway (API + Postgres) ──"
echo "  1. Add PostgreSQL plugin → copy DATABASE_URL"
echo "  2. Deploy API from repo (railway.toml → apps/api/Dockerfile)"
echo "  3. Required env:"
echo "       DATABASE_URL, JWT_SECRET (32+ chars), AUTO_SETTLE=false"
echo "       CORS_ORIGINS=https://web.vercel.app,https://app.vercel.app"
echo "       TELEGRAM_MODE=webhook"
echo "       TELEGRAM_BOT_TOKEN, TELEGRAM_WEBHOOK_URL, TELEGRAM_WEBHOOK_SECRET (16+)"
echo "  4. Optional: CIRCLE_API_KEY, CIRCLE_WALLET_ID, CIRCLE_SANDBOX=true"
echo "  5. Generate secrets: ./scripts/generate-staging-secrets.sh"
echo ""
echo "── Vercel (two projects) ──"
echo "  Project A — Root Directory: apps/web  (marketing, port 3100 local)"
echo "  Project B — Root Directory: apps/app  (dashboard, port 3001 local)"
echo "  Both need:"
echo "       NEXT_PUBLIC_API_URL=https://YOUR-API.up.railway.app"
echo "       NEXT_PUBLIC_WEB_URL=https://YOUR-WEB.vercel.app"
echo "       NEXT_PUBLIC_APP_URL=https://YOUR-APP.vercel.app"
echo ""
echo "── After deploy ──"
echo "  export NEXT_PUBLIC_API_URL=https://YOUR-API.up.railway.app"
echo "  export STAGING_WEB_URL=https://YOUR-WEB.vercel.app"
echo "  export STAGING_APP_URL=https://YOUR-APP.vercel.app"
echo "  ./scripts/staging-smoke.sh"
echo ""
echo "── Local Postgres (dev only) ──"
echo "  docker compose up -d postgres"
echo "  npm run db:migrate && npm run db:seed"
echo ""
echo "Never run db:seed on staging/production."
