#!/usr/bin/env bash
# Founder dashboard actions that cannot be automated from the repo (DNS, Supabase keys, GTM URLs).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "== VIRLUX founder security & launch checklist =="
echo ""
echo "Supabase (virlux-staging / bueoakgiisvufxfbdvoa):"
echo "  [x] Security Advisors — no CRITICAL (MCP verified)"
echo "  [ ] Rotate anon/publishable key — dashboard only (no API); then:"
echo "      bash scripts/setup-supabase-anon-probe.sh --set 'NEW_KEY' --verify"
echo "  [x] PostgREST probe — npm run verify:supabase-security"
echo ""
echo "DNS (dan.com registrar → Vercel):"
echo "  [x] virlux.com added to virlux-web (Vercel)"
echo "  [x] app.virlux.com added to virlux-app (Vercel)"
echo "  [ ] At dan.com: A virlux.com → 76.76.21.21"
echo "  [ ] At dan.com: A app.virlux.com → 76.76.21.21"
echo "  [ ] Remove /lander redirect on virlux.com"
echo "  Verify: npm run smoke:custom-domains"
echo ""
echo "Vercel env (Tier 3):"
echo "  [x] DEMO_SEED_PASSWORD + E2E_DEMO_PASSWORD (secrets vault)"
echo "  [ ] NEXT_PUBLIC_BOOK_DEMO_URL — Calendly (bash scripts/sync-founder-gtm-env.sh)"
echo "  [ ] NEXT_PUBLIC_DEMO_LOOM_URL — Loom embed"
echo "  [ ] NEXT_PUBLIC_ANALYTICS_DOMAIN — Plausible"
echo "  [x] contact@virlux.com seeded + MFA enrolled on staging"
echo "  [x] PLATFORM_ADMIN_MFA_REQUIRED=true on Vercel API (contact@ only — demo@ excluded from platform admin)"
echo ""
echo "Verify after changes:"
echo "  npm run verify:full"
echo ""
echo "Dashboard links:"
echo "  Supabase API keys: https://supabase.com/dashboard/project/bueoakgiisvufxfbdvoa/settings/api"
echo "  Web domains:       https://vercel.com/the-777-foundation/virlux-web/settings/domains"
echo "  App domains:       https://vercel.com/the-777-foundation/virlux-app/settings/domains"
echo ""
