#!/usr/bin/env bash
# Build .env.staging from local .env + generated secrets (gitignored — never commit)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f "$ROOT/.env" ]]; then
  echo "Missing .env — copy from .env.example"
  exit 1
fi

JWT=$(openssl rand -hex 32)
WEBHOOK=$(openssl rand -hex 16)

# Read telegram token from .env without printing
TELEGRAM_TOKEN=$(grep '^TELEGRAM_BOT_TOKEN=' "$ROOT/.env" | cut -d= -f2- || true)
CIRCLE_KEY=$(grep '^CIRCLE_API_KEY=' "$ROOT/.env" | cut -d= -f2- || true)
CIRCLE_WALLET=$(grep '^CIRCLE_WALLET_ID=' "$ROOT/.env" | cut -d= -f2- || true)

API_URL="${STAGING_API_URL:-https://YOUR-API.up.railway.app}"
WEB_URL="${STAGING_WEB_URL:-https://YOUR-WEB.vercel.app}"
APP_URL="${STAGING_APP_URL:-https://YOUR-APP.vercel.app}"

cat > "$ROOT/.env.staging" <<EOF
# Generated by staging-prepare-env.sh — DO NOT COMMIT
NODE_ENV=production
PORT=3002

DATABASE_URL=postgresql://USER:PASS@HOST:5432/railway

JWT_SECRET=${JWT}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL_DAYS=30

AUTO_SETTLE=false
SETTLEMENT_MODE=partner
ALLOW_ORG_DEPOSIT_CONFIRM=false
APPROVAL_THRESHOLD=5000
RATE_LIMIT_MAX=120
AUTH_RATE_LIMIT_MAX=10

CORS_ORIGINS=${WEB_URL},${APP_URL}

PLATFORM_ADMIN_EMAILS=contact@virlux.com,demo@virlux.com
DEPOSIT_WEBHOOK_SECRET=${WEBHOOK}

TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_BOT_NAME=VIRLUXBOT
TELEGRAM_MODE=webhook
TELEGRAM_WEBHOOK_URL=${API_URL}/api/telegram/webhook
TELEGRAM_WEBHOOK_SECRET=${WEBHOOK}
TELEGRAM_ADMIN_CHAT_IDS=

CIRCLE_API_KEY=${CIRCLE_KEY}
CIRCLE_SANDBOX=true
CIRCLE_WALLET_ID=${CIRCLE_WALLET}
CIRCLE_WEBHOOK_SECRET=

NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}
NEXT_PUBLIC_WEB_URL=${WEB_URL}
NEXT_PUBLIC_BOOK_DEMO_URL=
EOF

chmod 600 "$ROOT/.env.staging"
echo "Wrote .env.staging (gitignored)"
echo "After Railway/Vercel URLs are known, re-run with:"
echo "  STAGING_API_URL=... STAGING_WEB_URL=... STAGING_APP_URL=... bash scripts/staging-prepare-env.sh"
