#!/usr/bin/env bash
# Build .env.staging from local .env + generated secrets (gitignored — never commit)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f "$ROOT/.env" ]]; then
  echo "Missing .env — copy from .env.example"
  exit 1
fi

JWT=$(openssl rand -hex 32)
WEBHOOK=$(openssl rand -hex 16)

TELEGRAM_TOKEN=$(grep '^TELEGRAM_BOT_TOKEN=' "$ROOT/.env" | cut -d= -f2- || true)
CIRCLE_KEY=$(grep '^CIRCLE_API_KEY=' "$ROOT/.env" | cut -d= -f2- || true)
CIRCLE_WALLET=$(grep '^CIRCLE_WALLET_ID=' "$ROOT/.env" | cut -d= -f2- || true)

# Postgres for cloud staging — Supabase pooler; never sqlite
DB_URL="${DATABASE_URL:-}"
REF="${VIRLUX_SUPABASE_REF:-bueoakgiisvufxfbdvoa}"
PASS="${VIRLUX_STAGING_DB_PASSWORD:-}"
if [[ -z "$PASS" && -f "$HOME/.sina/secrets.env" ]]; then
  PASS=$(grep '^VIRLUX_STAGING_DB_PASSWORD=' "$HOME/.sina/secrets.env" | cut -d= -f2- || true)
fi
if [[ -n "$PASS" ]]; then
  ENC=$(python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$PASS")
  REGION="${VIRLUX_SUPABASE_REGION:-ca-central-1}"
  POOL_AWS="${VIRLUX_SUPABASE_POOL_AWS:-1}"
  DB_URL="postgresql://postgres.${REF}:${ENC}@aws-${POOL_AWS}-${REGION}.pooler.supabase.com:6543/postgres?pgbouncer=true"
elif [[ -z "$DB_URL" && -f "$ROOT/.env.staging" ]]; then
  DB_URL=$(grep '^DATABASE_URL=' "$ROOT/.env.staging" | cut -d= -f2- || true)
elif [[ -z "$DB_URL" && -f "$HOME/.sina/secrets.env" ]]; then
  DB_URL=$(grep '^DATABASE_URL=' "$HOME/.sina/secrets.env" | cut -d= -f2- || true)
fi
if [[ -z "$DB_URL" ]]; then
  DB_URL=$(grep '^DATABASE_URL=' "$ROOT/.env" | cut -d= -f2- || true)
fi
if [[ "$DB_URL" == sqlite:* ]] || [[ "$DB_URL" == *"USER:PASS@"* ]]; then
  echo "WARN: DATABASE_URL missing — set VIRLUX_STAGING_DB_PASSWORD in ~/.sina/secrets.env or run scripts/staging-supabase-db-url.sh"
  DB_URL="postgresql://USER:PASS@HOST:5432/postgres"
fi

API_URL="${STAGING_API_URL:-https://virlux-api.vercel.app}"
WEB_URL="${STAGING_WEB_URL:-https://virlux-web.vercel.app}"
APP_URL="${STAGING_APP_URL:-https://virlux-app.vercel.app}"
TELEGRAM_MODE="${TELEGRAM_MODE:-polling}"

cat > "$ROOT/.env.staging" <<EOF
# Generated by staging-prepare-env.sh — DO NOT COMMIT
NODE_ENV=production
PORT=3002

DATABASE_URL=${DB_URL}

JWT_SECRET=${JWT}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL_DAYS=30

AUTO_SETTLE=false
SETTLEMENT_MODE=partner
ALLOW_ORG_DEPOSIT_CONFIRM=false
DEMO_APPROVAL_THRESHOLD=100
DEMO_FUND_ENABLED=false
RATE_LIMIT_MAX=120
AUTH_RATE_LIMIT_MAX=10

CORS_ORIGINS=${WEB_URL},${APP_URL}

PLATFORM_ADMIN_EMAILS=contact@virlux.com,demo@virlux.com
DEPOSIT_WEBHOOK_SECRET=${WEBHOOK}

TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
TELEGRAM_BOT_NAME=VIRLUXBOT
TELEGRAM_MODE=${TELEGRAM_MODE}
TELEGRAM_WEBHOOK_URL=${API_URL}/api/telegram/webhook
TELEGRAM_WEBHOOK_SECRET=${WEBHOOK}
TELEGRAM_ADMIN_CHAT_IDS=

CIRCLE_API_KEY=${CIRCLE_KEY}
CIRCLE_SANDBOX=true
CIRCLE_WALLET_ID=${CIRCLE_WALLET}
CIRCLE_WEBHOOK_SECRET=

NEXT_PUBLIC_API_URL=${API_URL}
NEXT_PUBLIC_APP_URL=${APP_URL}
NEXT_PUBLIC_WEB_URL=${WEB_URL}
NEXT_PUBLIC_BOOK_DEMO_URL=
NEXT_PUBLIC_DEMO_MODE=true
NEXT_PUBLIC_DEMO_LOOM_URL=
NEXT_PUBLIC_ANALYTICS_DOMAIN=
EOF

chmod 600 "$ROOT/.env.staging"
echo "Wrote .env.staging (gitignored)"
echo "Re-run with URLs: STAGING_API_URL=... STAGING_WEB_URL=... STAGING_APP_URL=... bash scripts/staging-prepare-env.sh"
